baseURL: ""
languageCode: en-us
title: Virtuella Floran
theme: PaperMod

# params:
#   fuseOpts:
#     isCaseSensitive: false
#     # shouldSort: true
#     # location: 0
#     # distance: 1_000
#     # threshold:  0.4
#     # minMatchCharLength:  0

params:
    fuseOpts:
        ignoreLocation: true
        keys: ["title", "permalink", "summary", "content"]


outputs:
    home:
        - HTML
        - RSS
        - JSON

 

params:
  homeInfoParams:
    Title: "Bilder ur Nordens Flora (1917-1926)"
    Content: Carl Axel Magnus Lindman (1856–1928), botanist, Sweden. From runeberg.org

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  # ShowShareButtons: true

  ShowPostNavLinks: true

# languages:
#   en:
#     languageName: Engelska
#     contentDir: content
#     weight: 1
#   is:
#     languageName: Isländska
#     contentDir: content.is
#     weight: 2
#   sv:
#     languageName: Svenska
#     contentDir: content.se
#     weight: 2
        
menu: 
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: about virtuella
      url: /about/
      weight: -100
    - identifier: search
      name: Search
      url: /search/
      weight: -120

# params:
#     socialIcons:
#         - name: email
#           url: "mailto:blog@kpwn.de"
#         - name: twitter
#           url: "https://twitter.com/kwnypwny"
#         - name: github
#           url: "https://github.com/KwnyPwny"
#         - name: RSS
#           url: "/posts/index.xml" 